### ISSUE TITLE
Erreur de segmentation -f length

### ISSUE THREAD

**Issue by bertbreizh** [dalibo/pg_dumpacl#14] opened 2018-07-27 08:24 UTC
Hello, we have a problem with one server : 
Red Hat Enterprise Linux Server release 7.3 (Maip o)
When we use pg_dumpacl  ,we have on error : "Erreur de segmentation" 
krio:/applis/postgres>/usr/bin/pg_dumpacl -d postgres -f /savepostgres/krios521/pg/pgadv002/postgres_2018-07-26_10-50-52.createdb.sql
Erreur de segmentation

Postgres version : 9.6.6 
Pg_dumpacl : 
pg_dumpacl96.x86_64              0.2-1.el7.centos            @dalibolabs

in the /var/log/messages : 
Jul 27 09:36:55 krios521 kernel: pg_dumpacl[11721]: segfault at ffffffffffffffff ip 0000000000403476 sp 00007ffcdec50fd0 error 5 in pg_dumpacl[400000+6000]

When we redirect the file in /tmp is OK .

krio:/applis/postgres>/usr/bin/pg_dumpacl -d postgres -f /tmp/test.sql
krio:/applis/postgres>echo $?
0

krio:/applis/postgres/sh>/usr/bin/pg_dumpacl -d postgres -f /savepostgres/work/tmp/postgres5555.sql
krio:/applis/postgres/sh>/usr/bin/pg_dumpacl -d postgres -f /savepostgres/work/tmp/postgres55555.sql
Erreur de segmentation

The length of -f --> 39 character --> OK , 40 --> KO
Can you confirm ?
Thank you

**Comment by bertbreizh** [comment] 2018-07-27 11:11
Re, forget what i say , i think it is not datadomain .
krio:/applis/postgres/sh>/usr/bin/pg_dumpacl -d postgres -f /savepostgres/work/tmp/postgres5555.sql
krio:/applis/postgres/sh>/usr/bin/pg_dumpacl -d postgres -f /savepostgres/work/tmp/postgres55555.sql
Erreur de segmentation

The length of -f --> 39 character --> OK , 40 --> KO 
Can you confirm ? 
Thank you

**Comment by madtibo** [comment] 2018-07-27 12:33
Hello,

Does the '/savepostgres/krios521/pg/pgadv002' directory exist?
Does it work if you are creating the file in a local directory?

Cheers

**Comment by madtibo** [comment] 2018-07-27 13:02
Sorry, I did not see your message update.


I checked using files of length greater than 40 with no problem:
```
$ ./pg_dumpacl -p 5433 -f /tmp/123456789012345678901234567890.sql
$ ./pg_dumpacl -p 5433 -f /tmp/1234567890123456789012345678901234567890.sql
```

Do you reproduce your issue using the commands above?

**Comment by bertbreizh** [comment] 2018-07-27 14:10
krio:/usr/bin>./pg_dumpacl -p 5432 -f /tmp/123456789012345678901234567890.sql
krio:/usr/bin>echo $?
0
krio:/usr/bin>./pg_dumpacl -p 5432 -f /tmp/1234567890123456789012345678901234567890.sql
Erreur de segmentation

**Comment by madtibo** [comment] 2018-07-27 14:22
I am not able to reproduce your issue, either in 9.6 or 10.

It seems you are using an old minor version of PostgreSQL. Just to be sure, could you upgrade to latest minor version 9.6.9?

It should not change your problem. How did you install pg_dumpacl?
Could you try getting a traceback using gdb?

**Comment by bertbreizh** [comment] 2018-07-30 09:26
Hello . 
I think it's not pg_dumpacl ( for me Ok in 10 (Centos ) )
pg_dumpacl  is installed with dalibolabs repo : 
krio:/applis/postgres>yum list installed |grep pg_dumpacl
pg_dumpacl96.x86_64            0.2-1.el7.centos        @dalibolabs

I've installed gdb and debuginfo package , but I am not familiar with this tools

krio:/applis/postgres>**gdb /bin/pg_dumpacl**
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-110.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/pgsql-9.6/bin/pg_dumpacl...(no debugging symbols found)...done.
(gdb) **run -p 5432 -f /tmp/1234567890123456789012345678.sql**
Starting program: /bin/pg_dumpacl -p 5432 -f /tmp/1234567890123456789012345678.sql
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
**[Inferior 1 (process 20052) exited normally]**
(gdb) **run -p 5432 -f /tmp/1234567890123456789012345678901234567890.sql**
Starting program: /bin/pg_dumpacl -p 5432 -f /tmp/1234567890123456789012345678901234567890.sql
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".

**Program received signal SIGSEGV, Segmentation fault.**
0x00007ffff7bbcb4f in conninfo_array_parse (use_defaults=1 '\001', expand_dbname=<optimized out>, errorMessage=0x607b28, values=0x6070b0, keywords=0x607070) at fe-connect.c:4477
4477    fe-connect.c: Aucun fichier ou dossier de ce type.
(gdb) kill
Kill the program being debugged? (y or n) y
(gdb) quit

-->After 'yum update' , we are no on Red Hat 7.5 and we have always the error

**Comment by madtibo** [comment] 2018-07-31 18:04
I did reproduce your issue on a CentOS7 using dalibo labs package.
And comparing to pg_dumpall.c I found the problem: i was not initialising the pgdumpopts structure properly (it is a PQExpBuffer).
I will check tomorrow how to create a yum package you could try.

Thanks for the bug report!

**Comment by madtibo** [comment] 2018-08-01 15:36
Hello,
The package has been updated on the dalibolabs repo.
Tell me if your issue is solved.

Cheers,

**Comment by bertbreizh** [comment] 2018-08-02 08:06
Hello  , after upgrade pg_dumpacl we have always an error : 
```
**krio:/applis/postgres/log>gdb /bin/pg_dumpacl**
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-110.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/pgsql-9.6/bin/pg_dumpacl...(no debugging symbols found)...done.
(gdb) **run  -p 5432 -f /tmp/postgres_2018-08-02.createdb.sql**
Starting program: /bin/pg_dumpacl -p 5432 -f /tmp/postgres_2018-08-02.createdb.sql
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
**[Inferior 1 (process 5759) exited normally]**
**(gdb) run -p 5432 -f /tmp/postgres_2018-08-02_09-57-58.createdb.sql**
Starting program: /bin/pg_dumpacl -p 5432 -f /tmp/postgres_2018-08-02_09-57-58.createdb.sql
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".

**Program received signal SIGSEGV, Segmentation fault.**
0x00007ffff7bbab4f in conninfo_array_parse (use_defaults=1 '\001', expand_dbname=<optimized out>, errorMessage=0x607b28, values=0x6070b0, keywords=0x607070) at fe-connect.c:4477
4477    fe-connect.c: Aucun fichier ou dossier de ce type.

We have the new version : 
krio:/applis/postgres/log>yum list installed |grep dumpacl
Skipping unreadable repository '/etc/yum.repos.d/redhat.repo'
pg_dumpacl96.x86_64            0.3-1.el7.centos        @dalibolabs
krio:/applis/postgres/log>
```

**Comment by bertbreizh** [comment] 2018-09-04 08:41
Hello , no news ? 
We have installed on a new server ( postgres 9.6 , redhat7 ) and we have the same error 

tabb:/applis/postgres/sh>/usr/pgsql-9.6/bin/pg_dumpacl -p 3254 -f /tmp/1.sql
tabb:/applis/postgres/sh>echo $?
0
tabb:/applis/postgres/sh>/usr/pgsql-9.6/bin/pg_dumpacl -p 3254 -f /tmp/1234567890123456789012345678901234567890.sql
Memory fault
tabb:/applis/postgres/sh>

**Comment by madtibo** [comment] 2018-09-04 10:04
Hello,
I did not have time yet to investigate deeper why this error occurs.
It is quite strange since it does not happen on some platforms.
Is this bug blocking you from using pg_dumpacl?

**Comment by bertbreizh** [comment] 2018-09-04 11:45
Hello , no it's not blocking our production 
The script  ( pg_back : https://github.com/orgrim/pg_back/blob/master/pg_back )  use pg_dumpacl and we have an error . 
The dump is good , we just dont have the dumpacl export script .

**Comment by tilkow** [comment] 2018-09-06 17:47
Hello,
Can you try the new version, new RPM packages has been pushed on the dalibolabs repo.
Tell us if the errors are resolved.
Regards

**Comment by bertbreizh** [comment] 2018-09-07 06:01
Hello 
It works perfectly . 
Thanks !!

**Comment by tilkow** [comment] 2018-09-07 08:18
Great !

We close the issue. You can reopen it if the problem comes back.

**Closed as completed by tilkow** 2018-09-07 08:18 UTC
